import webbrowser
from PIL import Image
import streamlit as st
import pandas as pd
def app():
   def local_css(file_name):
        with open(file_name) as f:
            st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
   local_css("style2.html")
   st.markdown("<h1 style='text-align:center; color:red; font-family:archia;'>Insurance</h1>",unsafe_allow_html=True)
   col,buff1=st.columns(2)
   st.markdown("<h2 style='text-align:justify; color:black; font-family:archia;'>Health Insurance </h2>",unsafe_allow_html=True)
   st.write(" Health insurance is a type of insurance that covers medical expenses that arise due to an illness. These expenses could be related to hospitalisation costs, cost of medicines or doctor consultation fees.")
   col1,buff2=st.columns(2)
   img=Image.open("search.jpg")
   size=(500,600)
   img=img.resize(size)
   buff2.image(img)
   col1.markdown("<h2 style='text-align:justify; color:black; font-family:archia;'>10 Things to Know Before Buying a Health Insurance Policy</h2>",unsafe_allow_html=True)
   col1.markdown("<h4 style='text-align:justify; color:black; font-family:archia;'>1. The Age Criteria </h4>",unsafe_allow_html=True)
   col1.markdown("<h4 style='text-align:justify; color:black; font-family:archia;'>2. The Right Combination of Premium and Coverage</h4>",unsafe_allow_html=True)
   col1.markdown("<h4 style='text-align:justify; color:black; font-family:archia;'>3. The Waiting Period Clause </h4>",unsafe_allow_html=True)
   col1.markdown("<h4 style='text-align:justify; color:black; font-family:archia;'>4. Cashless Hospitalization Benefits</h4>",unsafe_allow_html=True)
   col1.markdown("<h4 style='text-align:justify; color:black; font-family:archia;'>5. Pre and Post Hospitalization Coverage</h4>",unsafe_allow_html=True)
   col1.markdown("<h4 style='text-align:justify; color:black; font-family:archia;'>6. Coverage of Maternity Expenses </h4>",unsafe_allow_html=True)
   col1.markdown("<h4 style='text-align:justify; color:black; font-family:archia;'>7. No-Claim-Bonus/No-Claim-Discount</h4>",unsafe_allow_html=True)
   col1.markdown("<h4 style='text-align:justify; color:black; font-family:archia;'>8. Preventive Health Check-up Facility </h4>",unsafe_allow_html=True)
   col1.markdown("<h4 style='text-align:justify; color:black; font-family:archia;'>9. Co-Payment Clause</h4>",unsafe_allow_html=True)
   col1.markdown("<h4 style='text-align:justify; color:black; font-family:archia;'>10. Claim Process</h4>",unsafe_allow_html=True)

   img=Image.open("care.jpg")
   size=(100,100)
   img=img.resize(size)
   col3,col4,col6=st.columns([0.5,8,1])
   col3.image(img)
   if col4.button("Cover : 5L , Cashless Hospitals : 154 ,Price : 1115/month , 13,369/Annualy"):
       webbrowser.open_new_tab("https://www.careinsurance.com/health-insurance/cr/health-insurance-plans-dk.html?agentId=20004977&utm_source=google&utm_medium=cpc&utm_campaign=ht_del_new-101_AD_CR_DT&utm_content=eta&utm_keyword=care%20health%20insurance&s_kwcid=AL!10397!3!462351757585!e!!g!!care%20health%20insurance&utm_term=11059271692&utm_adgroup=116886755668&gclid=Cj0KCQjw78yFBhCZARIsAOxgSx1Jhdjps6TuDMSh-8lMn_rlVSPZsStJSMi7IxknHuZWPirV2HWnlEcaAg2KEALw_wcB")
   img=Image.open("maxbupa.jpg")
   size=(100,100)
   img=img.resize(size)
   col3,col4,col6=st.columns([0.5,8,1])
   col3.image(img)
   if col4.button("Cover : 1 Cr , Cashless Hospitals : 234 ,Price : 1,794/month , 21,518/Annualy"):
     webbrowser.open_new_tab("https://www.maxbupa.com/health-insurance-plans/get-quote.html?cid=S_BR_E&utm_source=S_BR_E&utm_medium=GoogleSearch&utm_campaign=Brand-Exact&ef_id=Cj0KCQjw78yFBhCZARIsAOxgSx31HxtcA9iSf3JoJfrwvNnHeFkhfXLSV71cNyAmT8V7iMIJwXxF0tcaAiooEALw_wcB:G:s&s_kwcid=AL!7961!3!455146816934!e!!g!!maxbupa&ef_id=Cj0KCQjw78yFBhCZARIsAOxgSx31HxtcA9iSf3JoJfrwvNnHeFkhfXLSV71cNyAmT8V7iMIJwXxF0tcaAiooEALw_wcB:G:s&s_kwcid=AL!7961!3!455146816934!e!!g!!maxbupa&gclid=Cj0KCQjw78yFBhCZARIsAOxgSx31HxtcA9iSf3JoJfrwvNnHeFkhfXLSV71cNyAmT8V7iMIJwXxF0tcaAiooEALw_wcB")
   img=Image.open("birla.jpg")
   size=(100,100)
   img=img.resize(size)
   col3,col4,col6=st.columns([0.5,8,1])
   col3.image(img)
   if col4.button("Cover : 1 Cr , Cashless Hospitals : 319 ,Price : 1,719/month , 20,518/Annualy"):
     webbrowser.open_new_tab("https://lifeinsurance.adityabirlacapital.com/")
   img=Image.open("bjaja.jpg")
   size=(100,100)
   img=img.resize(size)
   col3,col4,col6=st.columns([0.5,8,1])
   col3.image(img)
   if col4.button("Cover : 5l , Cashless Hospitals : 266 ,Price : 1,652/month , 19,824/Annualy"):
      webbrowser.open_new_tab("https://www.bajajallianz.com/general-insurance.html?utm_source=GoogleBrandBagic&param1=Enhanced_Sitelink_RLSA&param2=Enhaced_Site_Link&param3=bajaj%20allianz&utm_content=SEM&gclid=Cj0KCQjw78yFBhCZARIsAOxgSx3g6U0ff3AwHBjoyNaTU3Zs8CVgg8bNXuRcqb2cv3ryKCntHWh10N8aAsuzEALw_wcB&gclsrc=aw.ds")
   img=Image.open("digit.jpg")
   size=(100,100)
   img=img.resize(size)
   col3,col4,col6=st.columns([0.5,8,1])
   col3.image(img)
   if col4.button("Cover : 5l , Cashless Hospitals : 279 ,Price : 975/month , 11,697/Annualy"):
      webbrowser.open_new_tab("https://www.godigit.com/?ts_v=202105030153402&s_kwcid=AL!11829!3!523462443570!e!!g!!digit%2520insurence&utm_source=google&utm_medium=cpc&utm_campaign=AO-Brand_Digit_Pure_New_EX&utm_content=Pure_Brand_Core&utm_term=digit%2520insurence&gclid=Cj0KCQjw78yFBhCZARIsAOxgSx3sQEnq04cn-uzKnRT1hbTC0-Ykehh7PIp1OymlDcAKkVKl71DpAL4aAhGjEALw_wcB")
   st.markdown("<h1 style='text-align:justify; color:black; font-family:archia;'>Government Certified Broker List</h1>",unsafe_allow_html=True)
   df = pd.read_excel("insurance.xlsx")
   df = df.drop(["Sl No"],axis=1)
   df = df.drop(["Unnamed: 2"],axis=1)
   st.table(df)
   img = Image.open(("Capture.png"))
   buff, col, buff = st.columns([4.5, 3, 4.5])
   col.image(img)
   buff, col4, buff = st.columns(3)
   col.markdown( "<h5 <p style ='font-family:archia; text-align: center; color: grey;'>We stand with everyone fighting on the frontlines</p></h5>",unsafe_allow_html=True)